# Generated by Django 4.2.5 on 2023-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_category_task_remove_album_artist_delete_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='rating',
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
